const defaultFighters = [
  // { id: 1,  name: "POWER", image: "xvlad.jpeg", attributes:                     { style: 168, agility: 161, speed: 155 } },
  { id: 1,  name: "xvlad", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pstzeKPDS7vrX2uvhVgjmVp33RGzRTS3tjtaXNtEeB2dga2AeYdkXJdB7gH5kvsWeQS2J7NiwskTibvGfKgyiecBN62WS?format=match&mode=fit", 
    attributes: { style: 68, agility: 61, speed: 55 } },
  { id: 2,  name: "alexandrefeliz", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssSKEvqs4nvVguz43WW66uUWZkg1y7SGNv12wgt9mCueotBEpNDaePMBCD2Zefs4J5iEWF7g8g2RpDYSbrpGqvBbDvBp?format=match&mode=fit", 
    attributes:   { style: 73, agility: 65, speed: 62 } },
  { id: 3,  name: "mengao", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssbhj8pSpdLJkLEDbCAd5Wj5ueVZrXCYaMXiLQ96Xqxqm2HKg4kBBhT72SaN4TqabEvbgJ5smGFKLDvhrT9H5vkJ4MqG?format=match&mode=fit", 
    attributes: { style: 62, agility: 59, speed: 60 } },
  { id: 4,  name: "vaipraonde", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssJb9KqQ5MP2ws1Jj6THwajCQaieFYuupbTy4TDXEXcJsssfVz2DDLnmH8yybs4ZGK7x9GJZBGMv6UXZgiHm4TVMgo1Q?format=match&mode=fit", 
    attributes: { style: 71, agility: 72, speed: 58 } },
  { id: 5,  name: "devferri", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssRDTL3DPpZoLrTQwZfABnw3wqtmvHQyVtJD5KDdZKe1R6GVn2yapWiCSjaDLS7MshRbEKwTupq6wKrgNyuAQfn8t5nW?format=match&mode=fit", 
    attributes: { style: 59, agility: 48, speed: 82 } },
  { id: 6,  name: "r4topunk", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssGZkcnUkJJpyJTt8JW5vkmVDkhnYPwL8mA44RW7dAS6XJ6ugvUswoTb5VKpJargDNsF1ZataFaNkyoNHHvy8oDTFmq8?format=match&mode=fit", 
    attributes: { style: 52, agility: 63, speed: 82 } },
  { id: 7,  name: "fonestreet", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6psu7GXp1rfrgWgwtn4ZBBnM7DrVREGoAxvfWQ5Mqsh4TxrGMqbdLoiBzELiQSrCEBubhH1ibknj1Fjnn8gdu76j8234Kg?format=match&mode=fit", 
    attributes: { style: 76, agility: 58, speed: 61 } },
  { id: 8,  name: "knowhow92", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssVTvGL4qQpUGrAXdNjBfdFt2M2L5miu5dpQiH9tWuWF8cCMhxwJME8ZWvuqYJhX5WKsZ3JyokkHAsZFXknTmjrUuXnE?format=match&mode=fit", 
    attributes: { style: 53, agility: 41, speed: 61 } },
  { id: 9,  name: "ezekhiveadict", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssTUqxb6rurM8jNBPhoPMwtM4fsGAzabKxGUKCAgLu5WUqQtojiKqH6gtx1psRyEvJ9tYf5D4yKpT7ThJS2c5ogvtsvv?format=match&mode=fit", 
    attributes: { style: 64, agility: 79, speed: 56 } },
  { id: 10, name: "louzado", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssH1GoA2HpLgasQDMghoGhz83u12D16aZX54fMhBEzb8NBsurQszoNuR857xVq6sgyh5Wy4rNfr9uW6WJwKtB7roEuJv?format=match&mode=fit", 
    attributes: { style: 54, agility: 64, speed: 60 } },
  { id: 11, name: "laribf", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pstze9AaH9LsmPPUWoDXhFNKAbToVRFQgtGCJc3pUqhZdsVszSrv6XbhT4LQVPNM4dCesEPoX3UKYzxQDQPMdyMCA5sFc?format=match&mode=fit", 
    attributes: { style: 81, agility: 74, speed: 64 } },
  { id: 12, name: "beaglexv", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6psshrREkSNTcdRDH3xmZex8NSef8XzDYF1d9shKoe7kN3VuqM7fp4YxTszqAqqv2ZQhAkpNBodrnr1F7FxERuEUssXeXQ?format=match&mode=fit", 
    attributes: { style: 74, agility: 74, speed: 71 } },
  { id: 13, name: "vasconsa", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssUJqmZytows821ZwEchpTyTWh3LTCzVAcewScyKkKoLn8fZRFJ6Xm2hDpjZrcViRnsQFjYDsuw4ny5h4pmFqi8seM1G?format=match&mode=fit", 
    attributes: { style: 63, agility: 64, speed: 61 } },
  { id: 14, name: "grafvisionsp", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssh9TrH5JUtmW6Jwt6SW1n5SnjvUvpbngFMJqrDXQF6UN82o9RnkNCF6dLeMs4bG3XEsEqLzeG4SAiEuxme3NTyDWX9Q?format=match&mode=fit", 
    attributes: { style: 64, agility: 75, speed: 58 } },
  { id: 15, name: "xlety", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssGZkgT322baQtQexzFHDyRnfFUpeGAAwUuZh3mkPucg1wbsaPKqtfpgHa1B2PUnjtz7EkedFwU52uQUdufMw9UhknTQ?format=match&mode=fit", 
    attributes: { style: 65, agility: 65, speed: 61 } },
  { id: 16, name: "pamtech", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssXmSDQx1CLBu9aRxifFmU7P8nPVAVgLQ7jSQJUXWMo18NGjfJyAzLHQzyWV1CbwERv5eCdBrut6WDKbuysdNrQ2WeGN?format=match&mode=fit", 
    attributes: { style: 61, agility: 50, speed: 85 } },
  { id: 17, name: "blessskateshop", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssbG8VrJyMRw4dnAcD1GGVt3ZNzLfU8aAB2GnhaWsm9AJTHB3s84u7m4HgBgMnGErMh9ZeNzNT8wBdvWB5kch8nTpQdk?format=match&mode=fit", 
    attributes: { style: 63, agility: 50, speed: 85 } },
  { id: 18, name: "diegodigocuts", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssSKhKiZeZ6BMdWehnqdGkQKcZJa6S4dUGXhuiQc4w8gvaZGLDhHzbJ5BZV1aGzJcYNNXUMFP8uXR8abcrAsn8z8aTdY?format=match&mode=fit", 
    attributes: { style: 64, agility: 65, speed: 61 } },
  { id: 19, name: "web-gnar", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6psu2EoTrjSXvzbGHzNYk1qyg9wPDE9YgkU6Rrj2zxF7mGGCwoiaEMJpNQEMDpN4KGf5x1ZZmPzMnwFXCCyMmSbCNHjBRY?format=match&mode=fit", 
    attributes: { style: 72, agility: 66, speed: 70 } },
  { id: 20, name: "willdias", image: "https://images.hive.blog/p/4HFqJv9qRjVecs4xkhd5EvhidWEEBnn9tCVDBkBhQpUFvab78MhbU1VvGeRxpPpzupiqt6pssjtkfkysNvNPXy78yNTYcf9aVeQ3iZG1BmnLToMWqm9nhvPSQUk1TiHC4aEwTv39qFn8s1workXZB8jmzBrMEV3QKsL?format=match&mode=fit", 
    attributes: { style: 62, agility: 59, speed: 61 } },
];

const superHack = {
  id: 21,
  name: "superSK8",
  image: "superSK8.jpeg",
  attributes: { style: 200, agility: 200, speed: 200 },
};

// Check if the hack is enabled
const hackEnabled = localStorage.getItem("superSK8") === "1";
const allfighters = hackEnabled ? [...defaultFighters, superHack] : defaultFighters;
export const fighters = allfighters;
